const data = {
  projects: [
    {
      key: 0,
      projectName: 'Multi-Post Stories',
      projectImage: '../assets/Snapshoot-5.png',
      companyName: 'CANOPY',
      projectPosition: 'Front End Dev',
      projectDate: 2015,
      projectDescription: `A daily selection
      of
      privately personalized reads; no accounts or sign-ups required.`,
      projectTechnologies: ['html', 'css', 'JavaScript'],
      projectText: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
      liveLink: 'https://rotimiazeez.github.io/my-portfolio/',
      sourceLink: 'https://github.com/rotimiazeez/my-portfolio',
    },
    {
      key: 1,
      projectName: 'Multi-Post Stories',
      projectImage: '../assets/Snapshoot-1-lg.png',
      companyName: 'FACEBOOK',
      projectPosition: 'Full Stack Dev',
      projectDate: 2018,
      projectDescription: 'Experiment content creation feature that allow user to add to an existing story over the course of a day without spamming their friends.',
      projectTechnologies: ['html', 'Ruby on rails', 'css', 'JavaScript'],
      projectText: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi deleniti modi possimus, sunt qui incidunt magnam non error, id eaque est voluptatum. Saepe, nam! Voluptates odio ad blanditiis ipsam dignissimos, minima libero vel aliquid corrupti repellendus fuga soluta sed. Ratione distinctio illum ducimus. Dignissimos, qui, minima reiciendis at error, veritatis officiis hic officia magni commodi assumenda minus enim quis. Maxime obcaecati amet quos ex atque saepe ratione laboriosam sapiente cupiditate? Officiis laudantium rem ratione alias voluptatem earum quod iste esse!",
      liveLink: '#',
      sourceLink: '#',
    },
    {
      key: 2,
      projectName: 'Facebook 360',
      projectImage: '../assets/Snapshoot-2-lg.png',
      companyName: 'FACEBOOK',
      projectPosition: 'Full Stack Dev',
      projectDate: 2018,
      projectDescription: 'Exploring the future of media in Facebooks first Virtual Reality app; a place to discover and enjoy 360 photos and videos on Gear VR',
      projectTechnologies: ['html', 'Ruby on rails', 'css', 'JavaScript'],
      projectText: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
      liveLink: '#',
      sourceLink: '#',
    },
    {
      key: 3,
      projectName: 'Tonic',
      projectImage: '../assets/Snapshoot-3-lg.png',
      companyName: 'Uber',
      projectPosition: 'Front End Dev',
      projectDate: 2015,
      projectDescription: 'A smart assistant to make driving more safe, efficient, and fun by unlocking your most expensive computer: your car',
      projectTechnologies: ['html', 'css', 'JavaScript'],
      projectText: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi deleniti modi possimus, sunt qui incidunt magnam non error, id eaque est voluptatum. Saepe, nam! Voluptates odio ad blanditiis ipsam dignissimos, minima libero vel aliquid corrupti repellendus fuga soluta sed. Ratione distinctio illum ducimus. Dignissimos, qui, minima reiciendis at error, veritatis officiis hic officia magni commodi assumenda minus enim quis. Maxime obcaecati amet quos ex atque saepe ratione laboriosam sapiente cupiditate? Officiis laudantium rem ratione alias voluptatem earum quod iste esse!",
      liveLink: '#',
      sourceLink: '#',
    },
  ],
};
export default data;